"""remove not null contraint for album description

Revision ID: 1fa7d27453f5
Revises: 86e5b74b6b91
Create Date: 2024-09-21 18:20:37.853085

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1fa7d27453f5"
down_revision: Union[str, None] = "86e5b74b6b91"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = "86e5b74b6b91"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("album", "description", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("album", "description", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
