"""add datetime fields for all models

Revision ID: 34447c554f77
Revises: 9d1936e66caf
Create Date: 2024-09-23 06:52:31.204870

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "34447c554f77"
down_revision: Union[str, None] = "9d1936e66caf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = "9d1936e66caf"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "album",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            default=sa.text("now()"),
        ),
    )
    op.add_column(
        "album",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            onupdate=sa.text("now()"),
            default=sa.text("now()"),
        ),
    )
    op.add_column(
        "face",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
        ),
    )
    op.add_column(
        "face",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            onupdate=sa.text("now()"),
        ),
    )
    op.add_column(
        "person",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
        ),
    )
    op.add_column(
        "person",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            onupdate=sa.text("now()"),
        ),
    )
    op.add_column(
        "photo",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
        ),
    )
    op.add_column(
        "photo",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            onupdate=sa.text("now()"),
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            onupdate=sa.text("now()"),
        ),
    )

    op.execute('UPDATE "album" SET created_at = now(), updated_at = now()')
    op.execute('UPDATE "face" SET created_at = now(), updated_at = now()')
    op.execute('UPDATE "person" SET created_at = now(), updated_at = now()')
    op.execute('UPDATE "photo" SET created_at = now(), updated_at = now()')
    op.execute('UPDATE "user" SET created_at = now(), updated_at = now()')

    op.alter_column("album", "created_at", nullable=False)
    op.alter_column("album", "updated_at", nullable=False)
    op.alter_column("face", "created_at", nullable=False)
    op.alter_column("face", "updated_at", nullable=False)
    op.alter_column("person", "created_at", nullable=False)
    op.alter_column("person", "updated_at", nullable=False)
    op.alter_column("photo", "created_at", nullable=False)
    op.alter_column("photo", "updated_at", nullable=False)
    op.alter_column("user", "created_at", nullable=False)
    op.alter_column("user", "updated_at", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "updated_at")
    op.drop_column("user", "created_at")
    op.drop_column("photo", "updated_at")
    op.drop_column("photo", "created_at")
    op.drop_column("person", "updated_at")
    op.drop_column("person", "created_at")
    op.drop_column("face", "updated_at")
    op.drop_column("face", "created_at")
    op.drop_column("album", "updated_at")
    op.drop_column("album", "created_at")
    # ### end Alembic commands ###
