"""add uq_name_owner_id unique constraint to album model

Revision ID: 7d17a70d29d8
Revises: 1fa7d27453f5
Create Date: 2024-09-21 18:29:43.895538

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7d17a70d29d8"
down_revision: Union[str, None] = "1fa7d27453f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = "1fa7d27453f5"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_name_owner_id", "album", ["name", "owner_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_name_owner_id", "album", type_="unique")
    # ### end Alembic commands ###
