"""add datastore field to Photo

Revision ID: 885af97a21c8
Revises: c0aea1fcee2b
Create Date: 2024-09-19 23:29:32.684735

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "885af97a21c8"
down_revision: Union[str, None] = "c0aea1fcee2b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("photo", sa.Column("datastore", sa.String, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("photo", "datastore")
    # ### end Alembic commands ###
