"""alter album cover column type from str to uuid

Revision ID: ae65514adff9
Revises: 7d17a70d29d8
Create Date: 2024-09-21 20:26:20.045299

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision: str = "ae65514adff9"
down_revision: Union[str, None] = "7d17a70d29d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = "7d17a70d29d8"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "album",
        "cover",
        existing_type=sa.VARCHAR(),
        type_=UUID(as_uuid=True),
        existing_nullable=True,
        postgresql_using="cover::uuid",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "album",
        "cover",
        existing_type=UUID(as_uuid=True),
        type_=sa.VARCHAR(),
        existing_nullable=True,
        postgresql_using="cover::varchar",
    )
    # ### end Alembic commands ###
