album_mapping = {
    # Background Spots
    "background is a forest": "In the Heart of Nature",
    "background is a city skyline": "Urban Wonders",
    "background is a mountain": "Peaks and Valleys",
    "background has a sunset": "Golden Horizons",
    "background is a desert": "Desert Dreams",
    "background is a snowy landscape": "Winter Wonderland",
    "background has river": "By the River Side",
    "background is a park": "Day in the Park",
    "background is a beach": "Seaside Serenity",
    "background is an indoor office": "Workspaces",
    "background is a garden": "Garden Bliss",
    "background is a street": "City Streets",
    "background is a stadium": "Stadium Vibes",
    "background is a playground": "Playtime",
    "background has buildings": "Architectural Views",
    "background is a marketplace": "Market Scenes",
    "background is a cafe or restaurant": "Café Moments",
    "background is a library": "In the Library",
    "background is a swimming pool": "Poolside Fun",
    "background is a concert stage": "On the Stage",
    "background is a worship place": "Sacred Spaces",
    "background is a classroom": "Classroom Moments",
    "background is a parking lot": "Parking Spaces",
    "background has a bridge": "Bridging the Gap",
    # Events and Moments
    "day at school": "School Days",
    "sports event": "Game Time",
    "birthday party": "Birthday Celebrations",
    "celebration or party": "Moments of Celebration",
    "casual outdoor gathering": "Outdoor Gatherings",
    "meeting or conference": "Conferences & Meetings",
    "indoor leisure time": "Indoor Relaxation",
    "outdoor adventure": "Adventures Outdoors",
    "rainy day outdoors": "Rainy Day Vibes",
    "morning routine": "Morning Moments",
    "evening relaxation": "Evening Calm",
    "night out": "Nightlife",
    "outdoor festival": "Festival Fun",
    "travel or commute": "Journeys",
    "holiday celebration": "Holiday Joy",
    "leisure by the beach": "Beach Escapes",
    "playing with pets": "Pet Playtime",
    "exercising outdoors": "Outdoor Workouts",
    "working at a desk": "Work Mode",
    "performance on stage": "Performance Spotlight",
    "camping or hiking": "Camping & Trails",
    "visiting a landmark": "Landmark Visits",
    "market or shopping scene": "Market Moments",
    "dining at a restaurant": "Dining Delights",
    "walking in the city": "City Walks",
    "sunset or sunrise moment": "Sunrise & Sunset",
    # Food and Dining
    "breakfast table spread": "Breakfast Bliss",
    "lunch outdoors": "Outdoor Lunch",
    "evening snacks": "Snack Time",
    "coffee or tea time": "Coffee Breaks",
    "dinner setup": "Dinner Time",
    "desserts or sweets": "Sweet Treats",
    "fast food items": "Fast Food Fix",
    "barbecue or grill": "BBQ Moments",
    "buffet or feast": "Buffet Time",
    "picnic food": "Picnic Eats",
    "fresh fruits and vegetables": "Fresh Picks",
    "bakery or pastry display": "Bakery Delights",
    # Animals and Birds
    "dogs": "Dog Days",
    "cats": "Cat Chronicles",
    "birds in flight": "Birds in Motion",
    "wild animals in the forest": "Wildlife Encounters",
    "farm animals": "Farm Life",
    "sea creatures": "Underwater Wonders",
    "birds perched": "Bird Watch",
    "animals in a zoo": "Zoo Adventures",
    "insects or butterflies": "Tiny Creatures",
    "fish in water": "Aquatic Life",
    "pets indoors": "Indoor Companions",
    "wildlife on a trail": "Wild Trails",
    # Vehicles and Transport
    "cars in traffic": "City Traffic",
    "bikes on the road": "On the Road",
    "trains at the station": "Train Journeys",
    "airplanes in the sky": "Skyline Flyers",
    "boats on the water": "Waterway Sails",
    # Activities
    "driving a car": "Driving Moments",
    "riding a bike": "Bike Rides",
    "boarding a train": "Train Boarding",
    "flying in an airplane": "In the Sky",
    "sailing on a boat": "Sailing Adventures",
    "off-roading": "Off-Road Adventures",
    "loading cargo in vehicles": "Cargo & Transport",
    "waiting at a bus stop": "Bus Stop Moments",
    "car parking": "Parking Spots",
    "filling fuel": "Fueling Up",
}
